#!/usr/bin/python3

from waflib.Context import Context
from glob import glob
from pathlib import Path
import os

instruments = ['CentralPanel', 'SignalBoard']


def configure(ctx):
    pass


def build(ctx):
    for i in instruments:
        ctx(rule=f"blender -b -P ../model/generate.py -- {i}",
            source=["../model/generate.py", "../model/models.py", "../model/Materials.py", f"../model/{i}.py"], target=f"../{i}.blend")
