#!/usr/bin/python3

from glob import glob
from pathlib import Path
import os


instruments = ['US2']

def configure(ctx):
    pass


def build(ctx):
    for i in instruments:
        ctx(rule=f"blender -b -P ${{SRC}} -- {i}", source="../model/models.py",target=f"../{i}.blend")
