#!/usr/bin/python3

from waflib.Context import Context
from glob import glob
from pathlib import Path
import os
import platform

instruments = ['CentralPanel', 'Monitor', 'PU56', 'PU56Button']


def configure(ctx):
    pass


def build(ctx):
    sources = glob("./build/../model/*.py")
    abs = []
    for s in sources:
        abs.append(Path(s).relative_to(Path("./build")).as_posix())
    for i in instruments:
        ctx(rule=f"{ctx.env.BL} -b -P ../model/generate.py -- {i} {ctx.env.RENDER}",
            source=abs, target=f"../{i}.blend")
