#!/usr/bin/python3

from glob import glob
from pathlib import Path


instruments = ['US2', 'CentralPanel']


def configure(ctx):
    pass


def build(ctx):

    # Web generation -> index.html
    sources = ctx.path.ant_glob("public/*", recursive=True)
    sources += ctx.path.ant_glob("src/*", recursive=True)
    sources += ctx.path.ant_glob("yarn.lock")
    sources += ctx.path.ant_glob("package.json")
    sources += ctx.path.ant_glob("export_svg.js")
    ctx(rule="cd ../vectors && yarn && yarn build",
        source=sources, target="../../vectors/build/index.html")
    ctx(rule="cp ${SRC} ${TGT}", source=[
        "../../vectors/src/center_upper_texture.jpg"], target="../texture/CentralPanel.jpg")
    # SVG generation -> *.svg
    for i in instruments:
        print(i)
        ctx(rule=f"cd ../vectors && node ./export_svg.js {i}",
            source="../../vectors/build/index.html", target=f"../../vectors/build/{i}.svg")
    # Generate texture
    for i in instruments:
        print(i)
        ctx(rule="inkscape -o ${TGT} -d 300 ${SRC}",
            source=f"../../vectors/build/{i}.svg", target=f"../texture/{i}.png")
